name       : bash-completion
version    : '2.5'
release    : 10
source     :
    - https://github.com/scop/bash-completion/archive/2.5.tar.gz : c43b54ca3ae8d7228e5d871d5900398924d6853e0999adf155f876d5cb86253b
license    : GPL-3.0+
summary    : Bash Completion Files
component  : system.base
description: |
    Provides the bash completion system
devel      : yes
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-a-stateless-configuration.patch
    autoreconf -vfi
    %configure
build      : |
    %make
install    : |
    install -d -D -m 00755 $installdir/usr/share/bash-completion/completions
    %make_install

    install -D -m 00644 $pkgfiles/eopkg $installdir/usr/share/bash-completion/completions/eopkg
