name       : bash-completion
version    : '2.10'
release    : 17
source     :
    - https://github.com/scop/bash-completion/releases/download/2.10/bash-completion-2.10.tar.xz : 123c17998e34b937ce57bb1b111cd817bc369309e9a8047c0bcf06ead4a3ec92
license    : GPL-2.0-or-later
component  :
    - system.base
    - devel : system.devel
summary    : Programmable Completion for Bash
description: |
    bash-completion is a collection of shell functions that take advantage
    of the programmable completion feature of Bash 2.04 and later
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-a-stateless-configuration.patch
    %reconfigure
build      : |
    %make
install    : |
    install -dDm00755 $installdir/usr/share/bash-completion/completions
    %make_install

    install -Dm00644 $pkgfiles/eopkg $installdir/usr/share/bash-completion/completions/eopkg
