name        : bash-completion
version     : 2.1
release     : 7
source     :
    - https://bash-completion.alioth.debian.org/files/bash-completion-2.1.tar.bz2 : 2b606804a7d5f823380a882e0f7b6c8a37b0e768e72c3d4107c51fbe8a46ae4f
license     : GPL-3.0+
summary     : Bash Completion Files
description : |
    Provides the bash completion system
devel      : yes
setup      : |
    %patch -p1 < $pkgfiles/words_bad_array_subscript.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    cp -r $pkgfiles/eopkg %installroot%/usr/share/bash-completion/completions/
    cp -r $pkgfiles/pisi %installroot%/usr/share/bash-completion/completions/
    rm %installroot%/usr/share/bash-completion/completions/hwclock
    #Conflict with util-linux or network-manager packages:
    rm %installroot%/usr/share/bash-completion/completions/ionice
    rm %installroot%/usr/share/bash-completion/completions/nmcli
    rm %installroot%/usr/share/bash-completion/completions/look
    rm %installroot%/usr/share/bash-completion/completions/rtcwake
    rm %installroot%/usr/share/bash-completion/completions/cal
    rm %installroot%/usr/share/bash-completion/completions/renice
    rm %installroot%/usr/share/bash-completion/completions/dmesg
    rm %installroot%/usr/share/bash-completion/completions/hexdump
    rm %installroot%/usr/share/bash-completion/completions/eject
