name        : bash-completion
version     : 2.1
release     : 8
source     :
    - https://bash-completion.alioth.debian.org/files/bash-completion-2.1.tar.bz2 : 2b606804a7d5f823380a882e0f7b6c8a37b0e768e72c3d4107c51fbe8a46ae4f
license     : GPL-3.0+
summary     : Bash Completion Files
description : |
    Provides the bash completion system
devel      : yes
setup      : |
    %patch -p1 < $pkgfiles/words_bad_array_subscript.patch
    %patch -p1 < $pkgfiles/0001-Use-a-stateless-configuration.patch
    autoreconf -vfi
    %configure
build      : |
    %make
install    : |
    install -d -D -m 00755 $installdir/usr/share/bash-completion/completions
    %make_install
    
    provided=(eopkg pisi)
    for prov in "${provided[@]}" ; do
        install -D -m 00644 $pkgfiles/${prov} $installdir/usr/share/bash-completion/completions/${prov}
    done
    
    # Conflict with other packages
    
    conflicts=(hwclock ionice nmcli look rtcwake cal renice dmesg hexdump eject)
    for con in "${conflicts[@]}" ; do
        rm -v $installdir/usr/share/bash-completion/completions/${con}
    done
